const actions = {
    GET_FOODS_CATEGORIES: 'GET_FOODS_CATEGORIES',
    SET_FOODS_CATEGORIES: 'SET_FOODS_CATEGORIES',
    GET_MERCHANTS_LISTS: 'GET_MERCHANTS_LISTS',
    SET_MERCHANTS_LISTS: 'SET_MERCHANTS_LISTS',
}
export default actions
