const actions = {
    SET_AUTH_STATE: 'SET_AUTH_STATE',
    SET_NUMBER: 'SET_NUMBER',
    VERIFY_OTP: 'VERIFY_OTP',
    LOG_OUT: 'LOG_OUT',
    REGISTER_USER: 'REGISTER_USER',
    CHEK_REGISTER_USER_FOR_GOOGLE: 'CHEK_REGISTER_USER_FOR_GOOGLE',
    REGISTER_USER_FOR_GOOGLE: 'REGISTER_USER_FOR_GOOGLE',
}
export default actions
